feat#116: int with default thresholds
GreenmaskIO/greenmask pull request #130
Opened 2024-05-22 06:56 UTC by DrSequence

2024-05-22 16:31 UTC, wwoytenko requested changes
Consider how to overcome the mentioned.

As I understand it resolves #116

2024-05-22 16:31 UTC, wwoytenko commented on internal/generators/transformers/noise_timestamp.go
> +		return nil, int_utils.ErrWrongLimits
Consider adding another import alias, because `int_utils` contains not only `integer` utils

2024-05-22 16:31 UTC, wwoytenko commented on internal/generators/transformers/random_int64.go
> +			minValue = minThreshold
The `0` value might be received from parameters. Consider the way how to overcome this obstacle. For instance, we would receive the values by pointer and if there is a nil, then set default value thresholds. 

`Parameterizer` interface provides the next method

```go
IsEmpty() (bool, error)
```

You can check that the value is empty if needed

2024-06-27 12:44 UTC, closed without merging

2024-06-27 12:44 UTC, DrSequence commented
I'll open new!